version: '3.6'

services:
  app1:
    build:
      context: ./
    volumes:
      - .:/app/:delegated
#      - ./yarn.lock:/app/yarn.lock
#      - ./data/app1_dist:/app/dist
      - ./data/app1:/app/data:delegated
      - ./data/app1_node_modules:/app/node_modules:delegated
    ports:
      - 3100:3100
    command: bin/entrypoint.sh
    links:
      - darkpayd1
    depends_on:
      - darkpayd1
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3100
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=darkpayd1
      - MAINNET_PORT=56667
      - TESTNET_PORT=46668

  app2:
    build:
      context: ./
    volumes:
      - .:/app/:delegated
#      - ./yarn.lock:/app/yarn.lock
#      - ./data/app2_dist:/app/dist
      - ./data/app2:/app/data:delegated
      - ./data/app2_node_modules:/app/node_modules:delegated
    ports:
      - 3200:3200
    command: bin/entrypoint.sh
    links:
      - darkpayd2
    depends_on:
      - darkpayd2
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3200
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=darkpayd2
      - MAINNET_PORT=56667
      - TESTNET_PORT=46668

#  gui1:
#    image: market-gui
#    build:
#      context: ../darkpay-desktop
#      dockerfile: Dockerfile
#    volumes:
#      - ../darkpay-desktop/:/app/:delegated
#      - ./data/gui1_node_modules:/app/node_modules:delegated
#    ports:
#      - 4300:4200
#    command: bin/entrypoint.sh
#    links:
#      - app1
#      - darkpayd1
#    depends_on:
#      - app1
#      - darkpayd1
#    environment:
#      - NODE_ENV=development
#      - GUI_ENV=docker1
#      - PORT=4200

#  gui2:
#    image: market-gui
#    build:
#     context: ../darkpay-desktop
#     dockerfile: Dockerfile
#    volumes:
#      - ../darkpay-desktop/:/app/:delegated
#      - ./data/gui2_node_modules:/app/node_modules:delegated
#    ports:
#      - 4400:4200
#    command: bin/entrypoint.sh
#    links:
#      - app2
#      - darkpayd2
#    depends_on:
#      - app2
#      - darkpayd2
#    environment:
#      - NODE_ENV=development
#      - GUI_ENV=docker2
#      - PORT=4200

  darkpayd1:
    image: ludx/darkpay:0.18.0.11 # master # 0.16.2.0
    volumes:
      - ./data/darkpay1:/root/.darkpay:cached
    ports:
      - 52935:46668
      - 52936:36668
      - 52938:46667
#    command: entrypoint.sh darkpayd -reindex-chainstate
    environment:
      - CONF_TESTNET=1                 # Use the test chain
      - CONF_RPCUSERNAME=test           # Username for JSON-RPC connections, generated unless set
      - CONF_RPCPASSWORD=test           # Password for JSON-RPC connections, generated unless set
#      - CONF_RPCPORT=52935
      - CONF_PRINTTOCONSOLE=0           # Send trace/debug info to console instead of debug.log file
#      - CONF_ONLYNET=onion              # Only connect to nodes in network: ipv4, ipv6 or onion
#      - CONF_PROXY=127.0.0.1:9050       # Connect through SOCKS5 proxy
#      - CONF_ONION=127.0.0.1:9050       # Use separate SOCKS5 proxy to reach peers via Tor hidden services (default: -proxy)
      - CONF_SERVER=1                   # Accept command line and JSON-RPC commands
#      - CONF_RPCALLOWIP=*
      - CONF_RPCALLOWIP=0.0.0.0/0       # Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
#      - CONF_REST=0                    # Accept public REST requests (default: 0)
      - CONF_LISTEN=1                   # Accept connections from outside (default: 1 if no -proxy or -connect)
#      - CONF_LISTENONION=1              # Automatically create Tor hidden service (default: 1)
#      - CONF_TORCONTROL=127.0.0.1:9051  # Tor control port to use if onion listening enabled (default: 127.0.0.1:9051)
#      - CONF_TORPASSWORD=darkpaytor     # Tor control port password, generated unless set
#      - CONF_DISCOVER=1                # Discover own IP address (default: 1 when listening and no -externalip)
#      - CONF_BIND=127.0.0.1             # Bind to given address and always listen on it. Use [host]:port notation for IPv6
#      - CONF_DEBUG=tor                    # Output debugging information: 0/1, addrman, alert, bench, cmpctblock, coindb, db, http, libevent, lock, mempool, mempoolrej, net, proxy, prune, rand, reindex, rpc, selectcoins, tor, zmq, qt.
      - CREATEDEFAULTMASTERKEY=true

  darkpayd2:
    image: ludx/darkpay:0.18.0.11 # master # 0.16.2.0
    volumes:
      - ./data/darkpay2:/root/.darkpay:cached
    ports:
      - 53935:46668
      - 53936:36668
      - 53938:46667
#    command: entrypoint.sh darkpayd -reindex-chainstate
    environment:
      - CONF_TESTNET=1                 # Use the test chain
      - CONF_RPCUSERNAME=test           # Username for JSON-RPC connections, generated unless set
      - CONF_RPCPASSWORD=test           # Password for JSON-RPC connections, generated unless set
      - CONF_PRINTTOCONSOLE=0           # Send trace/debug info to console instead of debug.log file
      - CONF_SERVER=1                   # Accept command line and JSON-RPC commands
      - CONF_RPCALLOWIP=0.0.0.0/0       # Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
      - CONF_LISTEN=1                   # Accept connections from outside (default: 1 if no -proxy or -connect)
      - CREATEDEFAULTMASTERKEY=true

